language: r
cache: packages

r:
  - oldrel
  - release
  - devel

before_cache:
  - Rscript -e 'remotes::install_cran("pkgdown")'
  - Rscript -e 'remotes::install_cran("RPushbullet")'
  - echo $TRAVIS_R_VERSION

deploy:
    provider: script
    script: Rscript -e 'pkgdown::deploy_site_github(); RPushbullet::pbPost("note",
                                  "Where did the name Jumping Rivers come from?",
                                  apikey = Sys.getenv("RPUSHBULLET"))'
    skip_cleanup: true
